name = "Unnamed Modpack"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64dea2f99dc8c74189ee5d81ef448ed3927c25d23e9a0eaf0c92b91143da24dd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
