name = "Unnamed Modpack"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd695ea534a2fa9abae34e8306b060bd0645f3fc9108a0053f2e7f0e4d83f0de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
