name = "Unnamed Modpack"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdd26893b25b3cdc877cdca9e317dc2a83c06c13f2557921c5bf793cd407699c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
