features:
  prevent-moving-into-unloaded-chunks: true
  item-merge-radius: 4.5

mob-spawning:
  categories:
    - category: "MONSTER"
      mobcap: 50
      spawn-interval: 4
      despawn-distance: 128

    - category: "CREATURE"
      mobcap: 8
      spawn-interval: 400
      despawn-distance: 128

    - category: "AMBIENT"
      mobcap: 2
      spawn-interval: 400
      despawn-distance: 128

    - category: "AXOLOTLS"
      mobcap: 2
      spawn-interval: 400
      despawn-distance: 128

    - category: "UNDERGROUND_WATER_CREATURE"
      mobcap: 2
      spawn-interval: 400
      despawn-distance: 128

    - category: "WATER_CREATURE"
      mobcap: 2
      spawn-interval: 400
      despawn-distance: 128

    - category: "WATER_AMBIENT"
      mobcap: 10
      spawn-interval: 200
      despawn-distance: 64
